apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "frp-operator.labels" . | nindent 4 }}
  name: proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: proxy-role
subjects:
- kind: ServiceAccount
  name: {{ include "frp-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
