# permissions for end users to edit exitservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "frp-operator.labels" . | nindent 4 }}
  name: exitserver-editor-role
rules:
- apiGroups:
  - frp.aureum.cloud
  resources:
  - exitservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - frp.aureum.cloud
  resources:
  - exitservers/status
  verbs:
  - get
