apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "frp-operator.labels" . | nindent 4 }}
  name: leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "frp-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
