# permissions for end users to edit exitservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: frp-operator
    app.kubernetes.io/managed-by: kustomize
  name: exitserver-editor-role
rules:
- apiGroups:
  - frp.aureum.cloud
  resources:
  - exitservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - frp.aureum.cloud
  resources:
  - exitservers/status
  verbs:
  - get
