---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - frp.aureum.cloud
  resources:
  - exitservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - frp.aureum.cloud
  resources:
  - exitservers/finalizers
  verbs:
  - update
- apiGroups:
  - frp.aureum.cloud
  resources:
  - exitservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - frp.aureum.cloud
  resources:
  - tunnels
  verbs:
  - get
  - list
  - watch
